language: csharp
# Mono is used to build .NET on Linux--we don't need it with Core.
mono: none
# Needed to run commands in the Xenial CLI
sudo: required
# The version of Ubuntu to run the Travis virtual machine -- needed for .NET Core
dist: xenial
# Your SDK version, not your run-time version
dotnet: 2.2
script: # These commands are executed in the Travis VM just like you would on your local machine
    # Use a "cd" command to move the Travis command line prompt into your solution directory
    - cd /home/travis/build/jdmac020/decisionTime/DecisionTime/
    # if your project has tests, you can skip "restore" and "build" and just use "test" command
    - dotnet test
    - cd ./DecisionTime.ThrowBack/
    - dotnet publish -c release -r win-x64 -o bin/dist/win-x64 --self-contained true
    - zip bin/dist/win-x64
    - dotnet publish -c release -r osx.10.14-x64 -o bin/dist/osx.10.14-x64 --self-contained true
    - zip bin/dist/osx.10.14-x64
    #-  dotnet publish -c release -r ubuntu.16.10-x64 -o bin/dist/ubuntu.16.10-x64
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name jdmac020
    - git config --local user.email john.macgregor@gmail.com
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $deploy_token
  file: 
    - /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/win-x64.zip
    - /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/osx.10.14-x64.zip
    #- /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/bin/dist/ubuntu.16.10-x64/DecisionTime.ThrowBack
  skip_cleanup: true