language: csharp
# Mono is used to build .NET on Linux--we don't need it with Core.
mono: none
# Needed to run commands in the Xenial CLI
sudo: required
# The version of Ubuntu to run the Travis virtual machine -- needed for .NET Core
dist: xenial
# Your SDK version, not your run-time version
dotnet: 2.2
script: # These commands are executed in the Travis VM just like you would on your local machine
    # Use a "cd" command to move the Travis command line prompt into your solution directory
    - cd /home/travis/build/jdmac020/decisionTime/DecisionTime/
    # if your project has tests, you can skip "restore" and "build" and just use "test" command
    - dotnet test
    - cd ./DecisionTime.ThrowBack/
    - dotnet tool install --global dotnet-warp
    - PATH=~/opt/bin:$PATH
    #- dotnet publish -c release -r win-x64 -o bin/dist/DecisionTime-Windows --self-contained true
    - dotnet-warp -r win-x64
    - mv DecisionTime.ThrowBack.exe DecisionTimeDemo.exe
    - zip DecisionTime-Windows.zip DecisionTimeDemo.exe
    - rm DecisionTimeDemo.exe
    - dotnet-warp -r osx-x64
    - ls
    #- dotnet publish -c release -r osx-x64 -o bin/dist/DecisionTime-Mac --self-contained true
    #- cd ./bin/dist/
    #- zip -r DecisionTimeDemo-Win.zip DecisionTime-Windows
    #- zip -r DecisionTimeDemo-Mac.zip DecisionTime-Mac
    #- curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
    #- unzip butler.zip
    # GNU unzip tends to not set the executable bit even though it's set in the .zip
    #- chmod +x butler
    # just a sanity check run (and also helpful in case you're sharing CI logs)
    #- ./butler -V
    #- ./butler push DecisionTimeDemo-Win.zip jdmac020/decision-time:windows10
    #- ./butler push DecisionTimeDemo-Mac.zip jdmac020/decision-time:osx
    #- zip -r DecisionTime-osx10-14-x64.zip DecisionTime-Mac
    #-  dotnet publish -c release -r ubuntu.16.10-x64 -o bin/dist/ubuntu.16.10-x64
#before_deploy:
    # Set up git user name and tag this commit
 #   - git config --local user.name jdmac020
  #  - git config --local user.email john.macgregor@gmail.com
   # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)}
   # - git tag $TRAVIS_TAG
#deploy:
 # provider: releases
  #api_key: $deploy_token
  #file: 
   # - /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/bin/dist/DecisionTime-win-x64.zip
    #- /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/bin/dist/DecisionTime-osx10-14-x64.zip
    #- /home/travis/build/jdmac020/decisionTime/DecisionTime/DecisionTime.ThrowBack/bin/dist/ubuntu.16.10-x64/DecisionTime.ThrowBack
  #skip_cleanup: true
  #prerelease: true
  #name: 'DecisionTime Demo'
  #body: 'Instructions for Play: Find your desired system (Windows10 x64 or MacOS 10.14) and download the zipped folder. Extract all, and find the executable application file named <DecisionTime.Throwback> and double-click. Your operating system and/or anti-virus may try to block the run because it does not recognize the program--you may need to manually override.'
  #on:
   # branch: master