language: csharp
# Mono is used to build .NET on Linux--we don't need it with Core.
mono: none
# Needed to run commands in the Xenial CLI
sudo: required
# The version of Ubuntu to run the Travis virtual machine -- needed for .NET Core
dist: xenial
# Your SDK version, not your run-time version
dotnet: 2.2
script:
    - cd /home/travis/build/jdmac020/decisionTime/DecisionTime/
    - dotnet test
    - cd ../Scripts/
    - chmod +x ./buterDeploy
    - chmod +x ./testWrap.bash
    - chmod +x ./test.bash
    - chmod +x ./testBreak.bash
    - ./testWrap.bash
    #- cd ./DecisionTime.ThrowBack/
    #- dotnet publish -c release -r win-x64 -o bin/dist/DecisionTime-Windows --self-contained true
    #- dotnet publish -c release -r osx-x64 -o bin/dist/DecisionTime-Mac --self-contained true
    #- cd ./bin/dist/
    #- zip -r DecisionTimeDemo-Win.zip DecisionTime-Windows
    #- zip -r DecisionTimeDemo-Mac.zip DecisionTime-Mac
    #- curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
    #- unzip butler.zip
    # GNU unzip tends to not set the executable bit even though it's set in the .zip
    #- chmod +x butler
    # just a sanity check run (and also helpful in case you're sharing CI logs)
    #- ./butler -V
    #- ./butler push DecisionTimeDemo-Win.zip jdmac020/decision-time:windows10
    #- ./butler push DecisionTimeDemo-Mac.zip jdmac020/decision-time:osx
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name jdmac020
    - git config --local user.email john.macgregor@gmail.com
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $deploy_token
  skip_cleanup: true
  prerelease: true
  name: 'DecisionTime Demo'
  body: 'Source code for the latest pre-release version of the DecisionTime demo.'
  on:
    branch: master
